version: '3'

services:
  api:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: api_bomappetite
    ports:
      - 3003:3003
      - 3005:3005
    restart: always
    volumes:
      - ./:/home/project_app/api
    tty: true
    networks:
      - bom_appetite_network

  db:
    image: mongo:4.4
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - /mongodb/dbdata:/data/db
      - /mongodb/configdb:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: user-database
    networks:
      - bom_appetite_network

networks:
  bom_appetite_network:
    driver: bridge
